### ISSUE TITLE
🐛 Multiple dots in file path passed to QuantumComputation::dump results in assertion fail

### ISSUE THREAD

**Issue by EliasLF** [cda-tum/mqt-core#446]
### Environment information

- mqt.core version: commit #433

### Description

When passing a file name containing more than 1 dot (e.g. `test.circuit.qasm`) to `QuantumComputation::dump` (or by extension any of its wrapper functions like `QuantumComputation::dumpOpenQASM`), the assertion in line 716 of `QuantumComputation.cpp` fails:
```java
assert(std::count(filename.begin(), filename.end(), '.') == 1);
```

If I understand this line correctly, it tries to assert, that the supplied file name includes a file extension (though I'm not quite sure, why this would even be necessary in line 716, where the dumping format is already clear; maybe this line actually belongs before current line 622 `const std::size_t dot = filename.find_last_of('.');`?).
In any case, if the only objective is to test for the existence of a file extension, shouldn't it be:
```java
assert(std::count(filename.begin(), filename.end(), '.') >= 1);
```

### Expected behavior

I would expect to be able to pass any valid file name (or even file path) to QuantumComputation::dump containing a valid quantum circuit file extension but no other constraints (and in case I supply an explicit `qc::Format` even the file extension to be irrelevant)

### How to Reproduce

```java
qc::QuantumComputation qc{4, 4};
qc.x(0, qc::Control{1});
qc.x(2, qc::Control{3});
qc.dump("test.circuit.qasm", qc::Format::OpenQASM);
// or
qc.dump("./test/circuit.qasm", qc::Format::OpenQASM); // second point not even in file name itself but only in parent path
```

**Comment by burgholzer** [comment]
Thanks for opening this issue. That is definitely a bug. I am kind of surprised that this wasn't really noticed earlier.

Just from looking at the function now, it would kind of make sense to have a check that:
- either the file has an extension already (>= 1 case)
- or an appropriate extension gets added (0 case)

Although, technically, I guess no input validation is required here anyway. As long as it's a valid filename, we shouldn't care.

Would you mind submitting a PR that resolves the problems and adds your two examples to the IO tests?

**Comment by EliasLF** [comment]
Sure, I just opened a PR resolving it. I went for the less constraining solution of just accepting any valid file name, if the format is specified (`QuantumComputation::dump(filename, format)`), and checking for >= 1 dot, when the format should be deduced from the file name (`QuantumComputation::dump(filename)`). If you disagree with that solution, feel free to edit my PR.
Thanks for your help/input!
