### ISSUE TITLE
Remove `qiskit-terra` dependency in favor of `qiskit`

### ISSUE THREAD

**Issue by 1ucian0** [cda-tum/mqt-core#580]
`mqt-core` depends on `qiskit-terra (>=0.22.0)`: https://www.wheelodex.org/projects/mqt-core/ which is reaching EoL:

> [!IMPORTANT]
> **The package `qiskit-terra` is not going to be updated after August 15th, 2024**. Since Qiskit 0.44 (released on July 27th, 2023), the `qiskit` meta-package only contains `qiskit-terra`. In Qiskit 1.0 and beyond, the meta-package architecture is removed.
> If you are installing or depending on `qiskit-terra`, consider changing that to `qiskit`: Either `qiskit>=0.x,<1` (if you did not transition to Qiskit 1.0 yet) or `qiskit>=0.x,<2` (to also include Qiskit 1.*).
> [Read more](https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0-installation#the-old-qiskit-structure).

**Comment by burgholzer** [comment]
Thanks for bringing this up.

The latest version (`2.3.0`) no longer depends on qiskit-terra, see https://github.com/cda-tum/mqt-core/blob/0b35f3e1101e5a655b765bbd2b08e29009eb034a/pyproject.toml#L64
So everything should be fine here.

wheelodex is showing the metadata for the 2.1.0 release, which predates Qiskit 1.0.
Apparently it refuses to read the metadata of the latest release as the corresponding wheels are too big.
