### ISSUE TITLE
Join Qiskit ecosystem

### ISSUE THREAD

**Issue by frankharkins** [cda-tum/mqt-core#728]
Thanks for maintaining MQT! Would you be interested in submitting `mqt-core` to the Qiskit ecosystem? It'd put the project in front of more users and on our radar so we know how Qiskit is being used. There's also the opportunity to present at a demo day and we'll sometimes reach out to offer support when changes happen in Qiskit. Any other MQT packages that use Qiskit (e.g. `mqt-qao`, `mqt-qcec`, `mqt-ddsim`) would be very welcome too, I only made the one issue to avoid spam.

Links:
* [Ecosystem web page](https://www.ibm.com/quantum/ecosystem)
* [Submission form](https://github.com/Qiskit/ecosystem/issues/new?template=submission.yml)

**Comment by burgholzer** [comment]
Hey Frank 👋🏻

Thank you for bringing this up! In fact, this has been on our mind since quite a while now. We'd love to become part of the Qiskit Ecosystem with our MQT and its tools. It just happens that we never really found the time to submit the respective applications.
I'll use this issue as a trigger for actually starting that process 😌👍🏻

**Comment by burgholzer** [comment]
It took a while, but I finally found some time to dedicate to this. I'll update this comment with references to the respective submissions:
- https://github.com/Qiskit/ecosystem/issues/815

**Comment by nquetschlich** [comment]
Some more Submissions:
- https://github.com/Qiskit/ecosystem/issues/823
- https://github.com/Qiskit/ecosystem/issues/825
- https://github.com/Qiskit/ecosystem/issues/827
- https://github.com/Qiskit/ecosystem/issues/829

**Comment by DRovara** [comment]
QUBOMaker is now also submitted

https://github.com/Qiskit/ecosystem/issues/831

**Comment by pehamTom** [comment]
QECC is also submitted.

* [[Submission]: MQT QECC Qiskit/ecosystem#837](https://github.com/Qiskit/ecosystem/issues/837)

**Comment by burgholzer** [comment]
All the created PRs have been merged. Happy to have the MQT as part of the Qiskit Ecosystem 🎉
